services:
  db:
    image: mysql:8.0
    container_name: bacon-distance-mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: bacon_distance
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-bacon-vol:/var/lib/mysql

  backend:
    build:
      context: ./bacon_distance/
      target: backend
    container_name: bacon-distance-backend
    ports:
      - 8000:80
    restart: "always"

  frontend:
    build:
      context: ./frontend/
      target: frontend
    container_name: bacon-distance-frontend
    ports:
      - 80:80
    restart: "always"
volumes:
  mysql-bacon-vol:
